apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-app
spec:
  template:
    spec:
      containers:
        - name: course-app
          resources:
             requests:
               cpu: 250m
               memory: 128Mi
             limits:
               cpu: 500m
               memory: 256Mi
